# Generated by Django 5.2.4 on 2025-08-08 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_material_remove_product_color_product_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_user', models.ImageField(blank=True, null=True, upload_to='photo/users/', verbose_name='Аватарка пользователя')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='BIO пользователя')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО пользователя')),
                ('register_data', models.DateField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
