# Generated by Django 5.2.4 on 2025-08-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fio',
        ),
    ]
