# Generated by Django 5.2.4 on 2025-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество покупок'),
        ),
    ]
